# Generated by Django 2.1 on 2019-04-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qiuz',
            new_name='Quiz',
        ),
    ]
