# Generated by Django 2.1 on 2019-04-04 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20190404_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='choices',
            new_name='choice1',
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='choice3',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
